version: "3.7"

networks: 
  postgres-pgadmin4:
    driver: bridge

services:
  pgadmin4:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres-pgadmin4
    restart: unless-stopped
    depends_on: 
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    hostname: pg
    networks: 
      - postgres-pgadmin4
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  pgadmin-data:
